# Generated by Django 4.2.7 on 2023-11-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_issue_priority_issue_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='issue',
        ),
        migrations.AddField(
            model_name='client',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('is_free', models.BooleanField(default=True, verbose_name='is free')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='main.issue')),
            ],
            options={
                'verbose_name': 'availability',
                'verbose_name_plural': 'availabilities',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='availability',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.availability'),
            preserve_default=False,
        ),
    ]
