# Generated by Django 4.2.7 on 2023-11-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_ticket_issue_client_activated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='availability',
        ),
    ]
