# Generated by Django 4.2.7 on 2023-11-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_ticket_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.availability'),
        ),
    ]
