# Generated by Django 4.2.7 on 2023-11-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ticket_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.availability'),
        ),
    ]
